name: Setup GIT token
description: GitHub Action that sets the GITHUB_TOKEN as credentials for git (enables `git push`)
author: Federico Brigante
branding:
  icon: chevron-up
  color: yellow
inputs:
  token:
    required: true
    description: The token provided by GitHub actions via secrets.GITHUB_TOKEN
  name:
    default: GitHub actions
    description: The name that will be used as "Author" of future commits
  email:
    default: actions@users.noreply.github.com
    description: The email that will be used as "Author" of future commits

runs:
  using: node12
  main: index.js
