name: CI
on:
  pull_request:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm test
    - name: Run Action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test the action by creating and deleting a tag
      run: |
        git tag testing-tag
        git push origin testing-tag
        git push --delete origin testing-tag
